### ISSUE TITLE
Login 页面设置了 footer: background: dark: 但是并未生效

### ISSUE THREAD

**Issue by 5t-RawBeRry** [mx-space/kami#1322]
```yaml
footer:
    background:
      src:
        dark: https://static.codemao.cn/sfs/album/elyu0gp4ebkz175cj65m848bqd8f966cj84mqosx.png
        light: /assets/footer.png
      position: top/cover
```

其他页面均显示正常 Login 有问题（

**Comment by ttimochan** [comment]
您好，请提供与原图大小一致的图片

**Comment by Innei** [comment]
请提供网站地址

**Comment by 5t-RawBeRry** [comment]
> 请提供网站地址

https://baka.cafe

顺带能请问可以始终为暗色主题吗？

**Comment by 5t-RawBeRry** [comment]
> > > 请提供网站地址
> > 
> > 
> > [baka.cafe](https://baka.cafe)
> > 顺带能请问可以始终为暗色主题吗？
> 
> 把 banDevtool 先关了，我这边不能去调试了

已经关闭了，谢谢大佬

**Comment by 5t-RawBeRry** [comment]
昨天 core 不是有更新嘛， 我把 docker 更新之后，会显示 ` module ' @mx-space/extra' not found`

**Comment by Innei** [comment]
你有魔改过 kami？

**Comment by Innei** [comment]
> 昨天 core 不是有更新嘛， 我把 docker 更新之后，会显示 ` module ' @mx-space/extra' not found`

@ttimochan 帮忙看下 docker 映射路径有没有生效。更新之后是不是丢失了

**Comment by 5t-RawBeRry** [comment]
> 你有魔改过 kami？

就加了两行css

**Comment by 5t-RawBeRry** [comment]
> 你有魔改过 kami？

```yaml
  custom:
    script: ''
    style: |-
      @media (prefers-color-scheme: dark) {
        .transform-gpu {
          filter: brightness(0.35);
        }
      }
      footer {
        padding: 1vw 0 2em !important;
      }
      .LampSwitch_select-container__GKO_y {
        display: none;
      }
    js: []
    css: []
```
